export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const FILTER_FAVORITES = 'FILTER_FAVORITES';
export const ORDER_FAVORITES = 'ORDER_FAVORITES';
export const ACTUALIZAR_FAVORITES = 'ACTUALIZAR_FAVORITES';

